### ISSUE TITLE
not workin with new version of reddit

### ISSUE THREAD

**Issue by innovinitylabs** [warnakey/delete-reddit-posts#1]
this is result

Attempting to login to Reddit with the provided Username and Password.
Successfully logged in to Reddit with the provided Username and Password.
This reddit account is using the old version of Reddit.
(node:9952) UnhandledPromiseRejectionWarning: Error: No node found for selector: span.user a
    at assert (C:\Users\xxx\Desktop\node_modules\puppeteer\lib\helper.js:267:11)
    at DOMWorld.click (C:\Users\xxx\Desktop\node_modules\puppeteer\lib\DOMWorld.js:366:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\xxx\Desktop\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (C:\Users\xxx\Desktop\node_modules\puppeteer\lib\Page.js:986:29)
    at run (C:\Users\xxx\Desktop\run.js:224:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by innovinitylabs** [comment]
Changing to old reddit in account settings got the job done. 


Also first time I entered password on web page instead of Command line

**Comment by warnakey** [comment]
I will probably end up remaking this program from scratch seeing as how this was made without the API and Reddit could change the new version at any time.
