### ISSUE TITLE
Error encountered

### ISSUE THREAD

**Issue by ThinkALot** [warnakey/delete-reddit-posts#2]
After installing node and npm I ran delete-reddit-posts and got the following error message:

Successfully logged in to Reddit with the provided Username and Password.
This reddit account is using the old version of Reddit.
(node:9332) UnhandledPromiseRejectionWarning: Error: No node found for selector: span.user a
    at assert (D:\Documents\Software\Delete Reddit Posts\node_modules\puppeteer\lib\helper.js:270:11)
    at DOMWorld.click (D:\Documents\Software\Delete Reddit Posts\node_modules\puppeteer\lib\DOMWorld.js:366:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async run (D:\Documents\Software\Delete Reddit Posts\run.js:224:2)
  -- ASYNC --
    at Frame.<anonymous> (D:\Documents\Software\Delete Reddit Posts\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (D:\Documents\Software\Delete Reddit Posts\node_modules\puppeteer\lib\Page.js:1031:29)
    at run (D:\Documents\Software\Delete Reddit Posts\run.js:224:13)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:9332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My default browser is Chrome in Windows 10, version 1903

**Comment by burnteloi** [comment]
I am getting same error

**Comment by warnakey** [comment]
Hi @ThinkALot and @burnteloi - Did you enter the username or password on the web page instead of in the Command line? That can cause that issue!


Please let me know.
